### ISSUE TITLE
unsatisfiable class OBI:comment on investigation

### ISSUE THREAD

**Issue by kaiiam** [hurwitzlab/planet-microbe-ontology#1]
unsatisfiable axiom [OBI:comment on investigation](http://purl.obolibrary.org/obo/OBI_0001898) when reasoned upon with ELK became inferred as owl:Nothing. 

I deleted it from PMO for now to get it to compile, however, the correct solution would be to figure out what is wrong with the axiom and request a change be made to the OBI term, which I suspect hasn't passed a rigorous ELK reasoner test. 

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/12255688/53939654-00c67900-4071-11e9-9893-11e2e899b6e2.png">

**Comment by kaiiam** [comment]
@cmungall assured me that OBI would have been reasoned on. 

Now I'm also getting similar issues with other terms PATO:[fluorescence](http://purl.obolibrary.org/obo/PATO_0000018) and ENVO:[fluorescence of water](http://purl.obolibrary.org/obo/ENVO_3100032). These along with OBI:[comment on investigation ](http://purl.obolibrary.org/obo/OBI_0001898) when reasoned with ELK 0.4.3 all come out as equivalent to owl:Nothing. 

I'm confused because when reasoned in ENVO, PATO:[fluorescence](http://purl.obolibrary.org/obo/PATO_0000018) and ENVO:[fluorescence of water](http://purl.obolibrary.org/obo/ENVO_3100032) don't have this issue. 

@cmungall if you get a chance could you have a look at this and try to help me figure out what's going on? Much appreciated!

**Comment by cmungall** [comment]
Nice work, you have found an unsatisfiable class in OBI! (note: classes are
unsatisfiable, you don't have unsatisfiable axioms; but you have
problematic axioms that lead to unsatisfiability)

Normally these things are to do with combining versions of ontologies but
this looks like a problem isolated to the source.

Can you open a ticket on the OBI tracker? (and link back here)

It's best practice to reproduce the error on the ontology in isolation when
doing such a bug report. But in this case I think the axiom is clearly
bonkers! You shouldn't combine a continuant and a process with an AND!! I
may use this example in an upcoming blog post on avoiding uneccesarily
complex axioms

I do touch on it here:
https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/

S3.1.3 Avoid conjunctions and disjunctions
